version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10

  pre_build:
    commands:
      - echo FRONT BUILD STARTS ON `date`
      - npm install

  build:
    commands:
      - npm run build
      - echo FRONT BUILD ENDS ON `date`

artifacts:
  files: [ '**/*' ]
  base-directory: build
